# Generated by Django 6.0.2 on 2026-02-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_managers_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
