# Generated by Django 6.0.2 on 2026-02-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('BTECH', 'B.Tech'), ('MTECH', 'M.Tech'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics & Comm'), ('MECH', 'Mechanical Eng'), ('CIVIL', 'Civil Engineering'), ('BBA', 'Business Admin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='O', max_length=1),
        ),
    ]
