# Generated by Django 6.0.2 on 2026-04-17 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_note_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('MECH', 'Mechanical'), ('BBA', 'Business Administration')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='voicesubmission',
            name='is_reviewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status', 'enrolled_at'], name='principal_e_status_fb29b8_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['due_date', 'created_at'], name='principal_h_due_dat_bc27d7_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesubmission',
            index=models.Index(fields=['is_reviewed', 'submitted_at'], name='principal_v_is_revi_76429c_idx'),
        ),
    ]
